language: ruby
rvm:
  - 2.2
  - 2.3.4
  - 2.4.1
  - jruby-9.1.10.0
env:
  - SPHINX_BIN=/usr/local/sphinx-2.0.10/bin SPHINX_VERSION=2.0.10
  - SPHINX_BIN=/usr/local/sphinx-2.1.9/bin SPHINX_VERSION=2.1.9
  - SPHINX_BIN=/usr/local/sphinx-2.2.6/bin SPHINX_VERSION=2.2.6
before_script:
- killall searchd; echo ''
- if (ruby -e "exit RUBY_VERSION.to_f >= 2.4"); then export RUBYOPT="--enable-frozen-string-literal"; fi; echo $RUBYOPT
after_script:
- killall searchd; echo ''
sudo: false
